name: Pull Request

on:
  pull_request:
    types: synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: odanado/deploy-to-netlify-action@test/v0.0.3
        with:
          dist-dir: public
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
